
CREATE TABLE tb_OrderLogRevNo
(
    ID INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    guid_key NVARCHAR(100) NULL,
    order_no NVARCHAR(100) NULL,
    num INT(4) NULL,
    po_number NVARCHAR(600) NULL,
    factory_code NVARCHAR(100) NULL,
    order_expdate NVARCHAR(100) NULL,
    invoice_cpyname NVARCHAR(510) NULL,
    invoice_addr TEXT NULL,
    invoice_email TEXT NULL,
    invoice_contact TEXT NULL,
    invoice_phone NVARCHAR(400) NULL,
    invoice_fax NVARCHAR(100) NULL,
    delivery_cpyname NVARCHAR(510) NULL,
    delivery_addr TEXT NULL,
    delivery_email TEXT NULL,
    delivery_contact NVARCHAR(400) NULL,
    delivery_phone NVARCHAR(400) NULL,
    delivery_fax NVARCHAR(100) NULL,
    item_ref1 NVARCHAR(300) NULL,
    item_ref2 NVARCHAR(300) NULL,
    item_ref3 NVARCHAR(300) NULL,
    item_ref4 NVARCHAR(300) NULL,
    item_ref5 NVARCHAR(300) NULL,
    item_ref6 NVARCHAR(300) NULL,
    item_ref7 NVARCHAR(300) NULL,
    item_ref8 NVARCHAR(300) NULL,
    item_ref9 NVARCHAR(300) NULL,
    style_number NVARCHAR(100) NULL,
    coo TEXT NULL,
    season_code NVARCHAR(100) NULL,
    colour NVARCHAR(300) NULL,
    gender NVARCHAR(300) NULL,
    remark TEXT NULL,
    content_number NVARCHAR(100) NULL,
    size_matrix_type NVARCHAR(400) NULL,
    size_content TEXT NULL,
    total_qty  NVARCHAR(100) NULL,
    artwork_number  NVARCHAR(100) NULL,
    brandid  NVARCHAR(300) NULL,
    order_user  NVARCHAR(100) NULL,
    order_date DATETIME(6) NULL,
    order_confirm_date DATETIME(6) NULL,
    is_draft   NVARCHAR(100) NULL,
    total_qty1  NVARCHAR(100) NULL,
    total_qty2  NVARCHAR(100) NULL,
    total_qty3  NVARCHAR(100) NULL,
    total_qty4  NVARCHAR(100) NULL,
    total_qty5  NVARCHAR(100) NULL,
    total_qty6  NVARCHAR(100) NULL,
    total_qty7  NVARCHAR(100) NULL,
    total_qty8  NVARCHAR(100) NULL,
    total_qty9  NVARCHAR(100) NULL,
    F1 TEXT NULL,
    F2 TEXT NULL,
    F3 TEXT NULL,
    F4 TEXT NULL,
    F5 TEXT NULL,
    F6 TEXT NULL,
    F7 TEXT NULL,
    F8 TEXT NULL,
    F9 TEXT NULL,
    F10  TEXT NULL,
    F11  TEXT NULL,
    F12  TEXT NULL,
    F13  TEXT NULL,
    F14  TEXT NULL,
    F15  TEXT NULL,
    F16  TEXT NULL,
    F17  TEXT NULL,
    F18  TEXT NULL,
    F19  TEXT NULL,
    F20  TEXT NULL,
    F21  TEXT NULL,
    F22  TEXT NULL,
    F23  TEXT NULL,
    F24  TEXT NULL,
    F25  TEXT NULL,
    F26  TEXT NULL,
    F27  TEXT NULL,
    F28  TEXT NULL,
    F29  TEXT NULL,
    F30  TEXT NULL,
    A_Content_Number NVARCHAR(100) NULL,
    B_Content_Number NVARCHAR(100) NULL,
    C_Content_Number NVARCHAR(100) NULL,
    invoice_addr2 TEXT NULL,
    invoice_addr3 TEXT NULL,
    delivery_city NVARCHAR(200) NULL,
    delivery_country NVARCHAR(200) NULL,
    delivery_post_code NVARCHAR(200) NULL,
    delivery_addr2 TEXT NULL,
    delivery_addr3 TEXT NULL,
    size_pointer VARCHAR(200) NULL,
    size_content1 TEXT NULL,
    size_content2 TEXT NULL,
    size_content3 TEXT NULL,
    size_content4 TEXT NULL,
    size_content5 TEXT NULL,
    size_content6 TEXT NULL,
    size_content7 TEXT NULL,
    size_content8 TEXT NULL,
    size_content9 TEXT NULL,
    size_content10 TEXT NULL,
    size_matrix_type1 NVARCHAR(400) NULL,
    size_matrix_type2 NVARCHAR(400) NULL,
    size_matrix_type3 NVARCHAR(400) NULL,
    size_matrix_type4 NVARCHAR(400) NULL,
    size_matrix_type5 NVARCHAR(400) NULL,
    size_matrix_type6 NVARCHAR(400) NULL,
    size_matrix_type7 NVARCHAR(400) NULL,
    size_matrix_type8 NVARCHAR(400) NULL,
    size_matrix_type9 NVARCHAR(400) NULL,
    size_matrix_type10 NVARCHAR(400) NULL,
    LocationCode TEXT NULL,
    Price1  NVARCHAR(40) NULL,
    Price2  NVARCHAR(40) NULL,
    Price3  NVARCHAR(40) NULL,
    Price4  NVARCHAR(40) NULL,
    Price5  NVARCHAR(40) NULL,
    Price6  NVARCHAR(40) NULL,
    Price7  NVARCHAR(40) NULL,
    Price8  NVARCHAR(40) NULL,
    Price9  NVARCHAR(40) NULL,
    currency1 VARCHAR(40) NULL,
    currency2 VARCHAR(40) NULL,
    currency3 VARCHAR(40) NULL,
    currency4 VARCHAR(40) NULL,
    currency5 VARCHAR(40) NULL,
    currency6 VARCHAR(40) NULL,
    currency7 VARCHAR(40) NULL,
    currency8 VARCHAR(40) NULL,
    currency9 VARCHAR(40) NULL,
    SumPrice VARCHAR(40) NULL,
    A_Preview TEXT NULL,
    B_Preview TEXT NULL,
    C_Preview TEXT NULL,
    AWExcel_Path VARCHAR(200) NULL,
    ShrinkagePorcentaje INT(4) NULL,
    DefaultSizeContent TEXT NULL,
    DraftOrderEmail NVARCHAR(400) NULL,
    IsWastage NVARCHAR(100) NULL,
    UpdateUser NVARCHAR(100) NULL,
    UpdateDate DATETIME(6) NULL,
    IsSendDrafEmail VARCHAR(30) NULL,
    AwReportFTPStatus NVARCHAR(20) NULL,
    OrderApiStatus CHAR(20) NULL,
    TrackingStatus NVARCHAR(100) NULL,
    item_ref10 NVARCHAR(300) NULL,
    total_qty10 NVARCHAR(100) NULL,
    Price10 NVARCHAR(40) NULL,
    currency10 NVARCHAR(40) NULL,
    EdiOrderNo NVARCHAR(100) NULL,
    Consolidated_ID NVARCHAR(100) NULL,
    Supplier_Code NVARCHAR(100) NULL,
    Send_Date NVARCHAR(100) NULL,
    Product_Description NVARCHAR(400) NULL,
    IsCopyOrder CHAR(30) NULL,
    AllowConfirmOrderDate NVARCHAR(100) NULL,
    SizeTableImg NVARCHAR(200) NULL,
    SizeContentNoMerged TEXT NULL,
    ArtWorkStatus CHAR(10) NULL,
    RePrintNum INT(4) NULL,
    RePrintedNum INT(4) NULL,
    RevNo INT(4) NULL,
    PDFCheckStatus CHAR(41) NULL,
    PoLastUpdateTime NVARCHAR(40) NULL,
    OptionId NVARCHAR(100) NULL,
    LeanAwReportFTPStatus CHAR(1) NULL,
    Order_Encryption NVARCHAR(100) NULL,
    AwXmlStatus NVARCHAR(400) NULL,
    qr_link TEXT NULL,
    EPCStatus NVARCHAR(400) NULL,
    FtpEcpStatus VARCHAR(100) NULL,
    FtpTidStatus VARCHAR(100) NULL,
    TempKey NVARCHAR(100) NULL,
    CreateDate DATETIME(6) NULL,
    QRPDFStatus CHAR(1) NULL,
    IntegrationXmlStatus  NVARCHAR(2) NULL,
    IntegrationXmlNum INT(4) NULL,
    CustomerId NVARCHAR(100) NULL,
    InvoiceAddressId NVARCHAR(100) NULL,
    InvoiceContactId NVARCHAR(100) NULL,
    DeliveryAddressId NVARCHAR(100) NULL,
    DeliveryContactId NVARCHAR(100) NULL,
    ERPEntityID NVARCHAR(100) NULL,
    MyAtexControl NVARCHAR(100) NULL
);

DESC tb_OrderLogRevNo;

INSERT INTO tb_OrderLogRevNo
(
    guid_key,
    order_no,
    num,
    po_number,
    factory_code,
    order_expdate,
    invoice_cpyname,
    invoice_addr,
    invoice_email,
    invoice_contact,
    invoice_phone,
    invoice_fax,
    delivery_cpyname,
    delivery_addr,
    delivery_email,
    delivery_contact,
    delivery_phone,
    delivery_fax,
    item_ref1,
    item_ref2,
    item_ref3,
    item_ref4,
    item_ref5,
    item_ref6,
    item_ref7,
    item_ref8,
    item_ref9,
    style_number,
    coo,
    season_code,
    colour,
    gender,
    remark,
    content_number,
    size_matrix_type,
    size_content,
    total_qty,
    artwork_number,
    brandid,
    order_user,
    order_date,
    order_confirm_date,
    is_draft,
    total_qty1,
    total_qty2,
    total_qty3,
    total_qty4,
    total_qty5,
    total_qty6,
    total_qty7,
    total_qty8,
    total_qty9,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    A_Content_Number,
    B_Content_Number,
    C_Content_Number,
    invoice_addr2,
    invoice_addr3,
    delivery_city,
    delivery_country,
    delivery_post_code,
    delivery_addr2,
    delivery_addr3,
    size_pointer,
    size_content1,
    size_content2,
    size_content3,
    size_content4,
    size_content5,
    size_content6,
    size_content7,
    size_content8,
    size_content9,
    size_content10,
    size_matrix_type1,
    size_matrix_type2,
    size_matrix_type3,
    size_matrix_type4,
    size_matrix_type5,
    size_matrix_type6,
    size_matrix_type7,
    size_matrix_type8,
    size_matrix_type9,
    size_matrix_type10,
    LocationCode,
    Price1,
    Price2,
    Price3,
    Price4,
    Price5,
    Price6,
    Price7,
    Price8,
    Price9,
    currency1,
    currency2,
    currency3,
    currency4,
    currency5,
    currency6,
    currency7,
    currency8,
    currency9,
    SumPrice,
    A_Preview,
    B_Preview,
    C_Preview,
    AWExcel_Path,
    ShrinkagePorcentaje,
    DefaultSizeContent,
    DraftOrderEmail,
    IsWastage,
    UpdateUser,
    UpdateDate,
    IsSendDrafEmail,
    AwReportFTPStatus,
    OrderApiStatus,
    TrackingStatus,
    item_ref10,
    total_qty10,
    Price10,
    currency10,
    EdiOrderNo,
    Consolidated_ID,
    Supplier_Code,
    Send_Date,
    Product_Description,
    IsCopyOrder,
    AllowConfirmOrderDate,
    SizeTableImg,
    SizeContentNoMerged,
    ArtWorkStatus,
    RePrintNum,
    RePrintedNum,
    RevNo,
    PDFCheckStatus,
    PoLastUpdateTime,
    OptionId,
    LeanAwReportFTPStatus,
    Order_Encryption,
    AwXmlStatus,
    qr_link,
    EPCStatus,
    FtpEcpStatus,
    FtpTidStatus,
    TempKey,
    CreateDate,
    QRPDFStatus,
    IntegrationXmlStatus,
    IntegrationXmlNum,
    CustomerId,
    InvoiceAddressId,
    InvoiceContactId,
    DeliveryAddressId,
    DeliveryContactId,
    ERPEntityID,
    MyAtexControl
)
VALUES
(
    "1234",
    "4234234",
    12,
    "2314214",
    "TESLA_34234",
    "2022-03-04 20:04:12",
    "invoice copyname",
    "invoice address",
    "invoice email",
    "07825432453",
    "+230543533",
    "245253",
    "245253",
    "John Doe",
    "INDIA_93242",
    "customer@gmail.com",
    "+243453453",
    "+246345235",
    "delivery fax",
    "ref 1",
    "ref 2",
    "ref 3",
    "ref 4",
    "ref 6",
    "ref 7",
    "ref 8",
    "ref 9",
    "ref 9",
    "style 1",
    "345345",
    "YELLOW",
    "MALE",
    "Remark content",
    "content num 2342423",
    "3452453",
    "4533",
    "34000",
    "345243",
    "345234",
    "user_34535",
    "2022-05-06 12:04:43",
    "2022-05-06 12:04:43",
    "DRAFTED",
    "2500",
    "2500",
    "2500",
    "2500",
    "2500",
    "2500",
    "2500",
    "2500",
    "2500",
    "F1 functionality",
    "F2 functionality",
    "F3 functionality",
    "F4 functionality",
    "F5 functionality",
    "F6 functionality",
    "F7 functionality",
    "F8 functionality",
    "F9 functionality",
    "F10  functionality",
    "F11  functionality",
    "F12  functionality",
    "F13  functionality",
    "F14  functionality",
    "F15  functionality",
    "F16  functionality",
    "F17  functionality",
    "F18  functionality",
    "F19  functionality",
    "F20  functionality",
    "F21  functionality",
    "F22  functionality",
    "F23  functionality",
    "F24  functionality",
    "F25  functionality",
    "F26  functionality",
    "F27  functionality",
    "F28  functionality",
    "F29  functionality",
    "F30  functionality",
    "A_content_num_234",
    "B_content_num_234",
    "C_content_num_234",
    "invoice addr 2",
    "invoice addr 3",
    "NEW DELHI",
    "INDIA",
    "PO.BOX.3453",
    "NEW DELHI",
    "NEW DELHI",
    "42353",
    "500",
    "500",
    "500",
    "500",
    "500",
    "500",
    "500",
    "500",
    "500",
    "700",
    "size matrix type1",
    "size matrix type2",
    "size matrix type3",
    "size matrix type4",
    "size matrix type5",
    "size matrix type6",
    "size matrix type7",
    "size matrix type8",
    "size matrix type9",
    "size matrix type10",
    "435000",
    "7000",
    "7000",
    "7000",
    "7000",
    "7000",
    "7000",
    "7000",
    "7000",
    "7000",
    "india rupee",
    "india rupee",
    "india rupee",
    "india rupee",
    "india rupee",
    "india rupee",
    "india rupee",
    "india rupee",
    "india rupee",
    "900000",
    "A Preview",
    "B Preview",
    "C Preview",
    "changes/copy.pdf",
    464,
    "9000",
    "draft@gmail.com",
    "Y",
    "342534534",
    "2022-03-06 20:04:05",
    "sendemail@gmail.com",
    "REPORTED",
    "OrderApi Status",
    "Tracking Status",
    "item ref10",
    "70000",
    "53000",
    "INDIA RUPPEE",
    "4523455",
    "4535345",
    "6300000",
    "2022-03-05 12:05:03",
    "Product Description",
    'Y',
    "2022-03-05 12:05:03",
    "500",
    "600",
    'Y',
    1200,
    1200,
    1200,
    "FOUND",
    "2022-03-05 12:05:03",
    "63000",
    'Y',
    "24535",
    "EDITED",
    "qr link",
    "EPCStatus_4523",
    "FtpEcpStatus_4523",
    "FtpTidStatus_4523",
    "TempKey_4523",
    "2022-03-05 12:05:03",
    'N',
    'K',
    300,
    "4352355",
    "INVOICE_345345",
    "4353543",
    "NEW DELHI",
    "99345333",
    "ERPEntity_9345",
    "My Atex Control"
);